import React, { Component } from 'react';
import {NORTH, EAST, SOUTH, WEST} from './constants';
import Grid from './elements/grid/grid';
import Controls from './elements/controls/controls';
import './App.scss';

/* MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXXXKXKKXXXXXXXXXXXXXXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXxc:cccccccccccccccclcclkNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXdlc:llllllllooollc::;,,;o0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOoo::ccc:::ccllllcc:;,,,;lOXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOkl;::colllllllllllc:;,',x00WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXO0kdkkkOOOOOOOOOOOOkkkxolxkxXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX0OkkkkkkkkkkkkkkkkxxxxkkkkkoOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWK0kxxxxdddddddddddddddddddxkoxWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXOOkxdloolcodddddddollollddxkodXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXooOkolxkkxl:lddddolldkkxl:oxkocxNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk,cOdcx0olO0l:dxxxl;d0olO0l:xkl,:0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx,lOxclxkkOd:lOkdxo:cxkkOxclxko';OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx;lOxdlcllcclxOkdoddcccllcodxko,;OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0;cOxddxxdxxdoddooodxxdddxddxkl'cKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMW0kOkdolccccccccccccccccccldxkddKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXOxd:;:::::::::;::::;::,:dxkkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOxdc;::;::::::::::::;;;cdxkk0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKxollcccccccccccccccccccldOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNXX0o;,,,,,,,'''''',,,,,,;;oO0KK00XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNWKdxOOkkxdoooololllloolooooododddxxkkd;:kNMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk0NkdO0OkkkkkxxxxkxxxxkkxxxxxxxxxxxkxkO0kllKMMMK0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNXOoOX0O0OkxdddddddddddddxxxxxdolcccldxxxOK0kkXMMM0x0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0dc.cOkkOko:;,,,,;;,,,,;codxdl:coddoc;cdxO00Ox0KKKo:coKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXxc:oOkkOxc.............:oddl;o0KXK00d;:xO00kx0XXXd:oxKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXxxXKkkOx:.....:;.  ...:odd::OXKkx0X0c;dO00kxXMMMOkXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNxlkNKxkOx:..   'ko.  ..;lddc;oK0O0XKk::x000kxXMMM0OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0:c0WKdxOxc'.....;;....';ldddc:ldxxdocldxO0KkkXMMM0kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO;,xW0odkkdlclccllclllllodxddddlcccclodxxO00kkXMMW0d0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO'.xW0ldkxxxocccccccccccc::::::cc::c::cldO00kkXMMNd:OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO,cKW0loxkkl;..........':;,'...'',,,...'lO0OkkXMMX:'kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMWNNNNNWM0:oNM0ooxOxc'..;:::.   .;,'.....:ddxo;..lO0OkONMMX:;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMWNKOxxkO0XKdOWMKooxkx:. .cccc'.''..;:cc:;.,oxxxd'.lO0Ok0WMMWolXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMN0OxOKOkxO0k0WMKooxkx:. .cccc'.;,'lxxkxxko,,;cc,..cO0Ok0WMMM0kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMXOOOKXKOkxolOWMKooxkx:. .cccc'.'''oxxxkxxdoocll; .cO0Ok0WMMM0OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMWXOOOOOOOk:.oNMKooxkx:. .''..'.   'cllllc;;;:ll, .ckOkkONMMWxc0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMW0kOOO0Ol.,kKkloxkxc'..''.',. .:...;c.':. .... .ckOkkONMMNl,OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMW0xdxxxo;.':lc:oxkxc'..'''''. ,d;..:o';d,.,:::..:xOkkONMMK:,OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMWOoolllc,.:xkdcldkxc,.,;,,,;,.':,..,:'':,.,;::..;dkkkkXMMK:lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMWNOocllllc;c0WMKlldkxc,,odollddc;cl;;cdc,cdc;ldd,.:dkkkkKMM0;xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMXxclxkdllloo0WMKoldxxl:;;;;;;::;,;;,,,:;,;:;,;;:;;cxkkkxKMMKoOMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMM0olxXNOocxOlxWMXdldxkxlc::::::::::::cccccccccccccodkkkkkXMM0dKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMNkooddolxKXodNMNkdxxxkxxddddddddddxxxxxxxxxxxxxxkkkkOkOOXMMOdNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMWX0OOOKWMWXXWMWKkkxdddddddddddddddddddddxxdxxdxxxxxxOOkKMWOOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXX0d;;,,;,;lc;;;:;;,,,;:::lolccldO0KXXWMMNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd,''''':0KOOO00Okdxx0OddollllONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd;;;,,,oXWMMMMMMMMMMMXkxdoood0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd::::;;dXWMMMMMMMMMMMXkxddddxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXdcccc:;l0WMMMMMMMMMMWKxkxdxxkXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXdclcc:;dXWMMMMMMMMMMWOdxxxxxkXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXdcccc:cOWMMMMMMMMMMMM0dxxxxxkXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKocccc:c0WMMMMMMMMMMMMKxxxxxxOXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkc::::;lKMMMMMMMMMMMMMKxddxxxOXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOxxoc;,,,,,,cKMMMMMMMMMMMMMKxdlllloxOXXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKo:;,,,,,,,,,;lKMMMMMMMMMMMMMKdc;'',,,;clokNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOl;;,,,,,,,,,,:oKMMMMMMMMMMMMMKo:,'''''''',:oKWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOl::;;;;;;;;,:lloOXXK00OOOO0KXXOo:''''''''',;;cONWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKddocccccccllloxdoxOOOkkkOOO00Okdc:;,','',,,,,;;ckNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNXNXXKKKKKXXXXXXXXNNNXXXXXXXXXXKx;;c:,,,,,,,,,;:coKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNXOOOkxddoollcclodkXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM */

class App extends Component {
  constructor(props){
    super(props);
    this.state = {
      x: 2,
      y: 2,
      direction: NORTH,
      speaking: false,
      error: false
    }

    this.directions = [NORTH, EAST, SOUTH, WEST];
    this.min = 0;
    this.max = 4;
  }

  outOfBounds = val => val < this.min || val > this.max;

  report = () => {
    this.setState({ speaking: true, error: false });
  }

  place = (x, y, facing) => {
    // place the robot at x and y, facing dir
    if (this.outOfBounds(x) || this.outOfBounds(y)) {
      this.setState({
        speaking: false,
        error: true
      });
    } else {
      this.setState({
        x,
        y,
        direction: facing,
        speaking: false,
        error: false
      });
    }
  }

  move = () => {
    // move one step forward
    // are we dealing with x or y? depends on direction
    const {x,y,direction} = this.state;
    switch(direction) {
      case NORTH:
        this.place(x, y+1, direction);
        break;
      case EAST:
        this.place(x+1, y, direction);
        break;
      case SOUTH:
        this.place(x, y-1, direction);
        break;
      case WEST:
        this.place(x-1, y, direction);
        break;
      default:
        return;
    }
  }

  left = () => {
    this.rotate(-1);
  }

  right = () => {
    this.rotate(1);
  }

  rotate = (dir) => {
    let dirIndex = this.directions.indexOf(this.state.direction);
    if (dirIndex === -1) {
      // this should never happen
      this.setState({
        speaking:false,
        error:true
      });
    }
    dirIndex = dirIndex + dir;
    // flip over
    if (dirIndex < 0) dirIndex = 3;
    else if (dirIndex > 3) dirIndex = 0;
    this.setState({
      direction: this.directions[dirIndex],
      speaking: false,
      error: false
    });
  }

  render() {
    const {x, y, direction, speaking, error} = this.state;
    return (
      <div className="App">
        <header className="App-header">
          <h1>Robot</h1>
          <h2>by Niall King</h2>
        </header>
        <main className="App-main">
          <Grid x={x} y={y} direction={direction} speaking={speaking} error={error} />
          <Controls onLeft={this.left} onRight={this.right} onMove={this.move} onPlace={this.place} onReport={this.report} />
        </main>
      </div>
    )
  }
}

export default App;
